Module8 task1
htmlacademy-javascript/1888983-kekstagram-2 pull request #7
Opened 2024-08-25 14:56 UTC by Obmazur

Настроил открытие/закрытие большого окна и генерацию данных для него. Поставил проверку на количество комментариев для счётчика (хотя он и скрыт).

2024-08-25 16:26 UTC, wonderjs requested changes
Сразу напишу про один критерий, который лучше заранее учесть при создании переменных. [Д6.](https://up.htmlacademy.ru/javascript-individual/2/criteries#d6) Используется единый стиль именования переменных.
Если ты будешь для переменных содержащих DOM-элемент добавлять постфикс Element, то нужно добавлять для всех. Плюсы такого подхода - ты всегда по названию переменной будешь понимать что это - дом элемент или данные. Минус  - надо будет пройтись по коду и добавить этот постфикс там где он нужен.

2024-08-25 16:26 UTC, wonderjs commented on js/comments.js
> +    const commentElement = commentTemplate.cloneNode(true);
Можно вынести клонирование и заполнение одного комментария в отдельную функцию getComment.

Ещё можно завести отдельный темплейт для комментария в index.html, по аналогии с миниатюрами
```
  <template id="comment">
    <li class="social__comment">
      <img
          class="social__picture"
          src=""
          alt=""
          width="35" height="35">
      <p class="social__text"></p>
    </li>
  </template>
```

2024-08-25 16:26 UTC, wonderjs commented on js/gallery.js
> +import {getPhotos} from './data.js';
Верни вызов getPhotos в модуль main, в этот модуль мы будем передавать массив фотографий через функцию

2024-08-25 16:26 UTC, wonderjs commented on js/gallery.js
> +  commentsLoader.classList.add('hidden');
Внутри этой функции должен быть вызов renderBigPicture и добавление обработчика onDocumentKeydown

2024-08-25 16:26 UTC, wonderjs commented on js/gallery.js
> +  body.classList.remove('modal-open');
Здесь также должно быть удаление обработчика onDocumentKeydown. Иначе получается, что при закрытии на Esc ты этот обработчик не удаляешь.

2024-08-25 16:26 UTC, wonderjs commented on js/gallery.js
> +    openBigPicture();
В функцию openBigPicture логично передавать нужный объект фотографии, а внутри вызывать renderBigPicture. Сейчас получается, что если клик произойдет между карточками, код двумя строчками ниже упадет с ошибкой, тк currentPicture не будет существовать, но мы попробуем вызвать renderBigPicture

2024-08-25 16:26 UTC, wonderjs commented on js/gallery.js
> +createThumbnails(photos, thumbnailListElement);
Сделай внутри модуля функцию инициализации галерии, где будет вызов рендера миниатюр + доабвление обработчика на контейнер
```
const initGallery = (photos) => {
  thumbnailListElement.addEventListener('click', (evt) => {
    if (evt.target.matches('.picture__img')) {
      const currentPicture = photos.find((photo) => photo.id === +evt.target.dataset.id);
      openBigPicture(currentPicture);
    }
  });

  createThumbnails(photos, thumbnailListElement);
};
```

2024-08-25 16:26 UTC, wonderjs commented on js/gallery.js
> +  commentCount.querySelector('.social__comment-shown-count').textContent = checkCommentsCount(comments);
Количество показанных комментариев логично заполнять в модуле комментариев, ведь внутри него мы будем изменять этот счетчик.

2024-08-25 16:26 UTC, wonderjs commented on js/gallery.js
> +const openBigPicture = () => {
Функции openBigPicture, renderBigPicture, closeBigPicture, onDocumentKeydown и обработчик на кнопку закрытия можно вынести в отдельный модуль big-picture. Экспортировать оттуда одну функцию openBigPicture и вызывать в этой модуле

2024-08-25 16:26 UTC, wonderjs commented on js/thumbnails.js
> +const createThumbnails = (photos, element) => {
Лучше не `element`, а `container` (если мы используем именование DOM-переменных без постфикса Element), либо `containerElement` (если используем постфикс)

2024-08-27 09:14 UTC, Obmazur commented
Пересмотрел нейминг, перенес основную массу кода в новый модуль, создал общую функцию галереи ну и поправил баги

2024-08-27 12:08 UTC, merged