Module9 task1
htmlacademy-javascript/1888983-kekstagram-2 pull request #9
Opened 2024-09-04 10:31 UTC by Obmazur

Настроил открытие/закрытие, отключение ESC в полях ввода, проверки полей и блокировку отправки.
Не придумал, как сделать проверке интерфейс и убрать лишние переменные в её файле.

2024-09-04 20:00 UTC, wonderjs requested changes

2024-09-04 20:00 UTC, wonderjs commented on index.html
> +                    <textarea class="text__description" name="description" placeholder="Ваш комментарий..." maxlength="140" data-pristine-maxlength-message="Не более 140 символов"></textarea>
Вместо maxlength нужно задать data-pristine-maxlength="140", иначе пользователь не увидит сообщение об ошибке и не поймет почему он не может дальше вводить символы

2024-09-04 20:00 UTC, wonderjs commented on js/form-validation.js
> +const MAX_HASTAGS = 5;
[Б10.](https://up.htmlacademy.ru/javascript-individual/2/criteries#b10) Список констант идёт перед основным кодом.

2024-09-04 20:00 UTC, wonderjs commented on js/form-validation.js
> +  return hastags;
избыточно создавать промежуточную переменную, если ты потом сразу возвращаешь ее из функции. Аналогично ниже

2024-09-04 20:00 UTC, wonderjs commented on js/form-validation.js
> +  const hastags = hastagTextElement.value.split(' ');
Здесь хорошо сразу привести хештег к одному регистру и отфильтровать пустые значения, если пользователь ввел несколько пробелов подряд

2024-09-04 20:00 UTC, wonderjs commented on js/form-validation.js
> +  const set = new Set;
Посмотри доку про [Set](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Set/Set)
Здесь должно быть `new Set(hashtags);` и тогда ниже цикл не нужен

2024-09-04 20:00 UTC, wonderjs commented on js/form-validation.js
> +  pristine.addValidator(hastagTextElement, validateLength, 'Не более 5 хэштегов');
5 лучше взять из константы

2024-09-04 20:00 UTC, wonderjs commented on js/form-validation.js
> +validateHastags();
это зачем?

2024-09-04 20:00 UTC, wonderjs commented on js/form-validation.js
> +const validateHastags = () => {
лучше назвать setHashtagsValidator

2024-09-04 20:00 UTC, wonderjs commented on js/form-validation.js
> +formElement.addEventListener('submit', (evt) => {
этот обработчик должен быть в модуле form, в здесь лучше создать функцию checkValidation / validateForm, внутри возвращать pristine.validate() + сделать функцию сброса ошибок валидации (resetValidation), которую вызвать при закрытии модалки, где внутри будет pristine.reset();
Обе функции экспортировать и вызывать в модуле form

2024-09-06 07:54 UTC, Obmazur commented on js/form-validation.js
> +const validateHastags = () => {
Удалил в целом эту функцию, оставив обработчики просто в модуле

2024-09-06 10:16 UTC, merged